### PR TITLE
Add media-radio/liquidsoap-1.3.7 and its dependencies

### PR DESCRIPTION
**Pull request by crocket**
It closes https://github.com/SpiderX/portage-overlay/issues/7 and https://github.com/SpiderX/portage-overlay/issues/8

### CODE REVIEW

**Comment by SpiderX** [comment]
@crocket Thanks for this. I had an intention to update liquidsoap, but if I recall correctly portage doesn't support something important that is needed by liquidsoap that stopped me.

I'm going to review your commits.

**Comment by crocket** [comment]
Note that ocaml-gstreamer is currently buggy and hangs during shutdown if liquidsoap tries to exit immediately after it is started.

**Comment by crocket** [comment]
I fixed dev-ml/ocaml-gstreamer-0.3.0 by applying a patch. It's now safe to merge the pull request.
After upgrading ocaml-duppy from 0.6.0 to 0.8.0 and fixing ocaml-gstreamer-0.3.0, I do not experience freezing during shutdown.

**Comment by SpiderX** [comment]
@crocket  Hi, thanks for your efforts. It really helped, however I can't merge this as is in various reasons, such as:
1. make commits atomic next time, please. It is hard to track changes when they are in one big commit and consists of lots of packages. One package — one commit.
2.  dev-ml/camomile. It is better to use opam use class for the latest camomile. It suppots build though opam and it makes ebuild much cleaner.
3. dev-ml/dune is in portage, but needs version bump to liquidsoap. It is better to just bump portage version of ebuild.
4. dev-ml/ocaml-duppy. You missed patch and package doesn't use camlp4.
5. dv-ml/ocaml-ffmpeg. There is a commit in repository that fixes parallel make. It is always good idea to backport code to fix such kind of issues.
6. dev-ml/ocaml-flac. You missed a patch and there were some others issues with dependencies that were missed by me in original ebuild.
7.  media-radio/liquidsoap. Some dependencies are too strict without reason; src_configure misses lots of configure options; interesting src_install, but since we have patches from old ebuild and we can reuse then in 1.3.7 it is better to go in this way, and systemd stuff should be installed unconditionally. 

I am going to close this. Next time make more atomic commits and I will be able to provide a more detailed code review.
Thank you!

**Pull request closed without merging**
